apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceo-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ceo-backend
  template:
    metadata:
      labels:
        app: ceo-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
