apiVersion: v1
kind: Service
metadata:
  name: ceo-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30005
  selector:
    app: ceo-backend
