apiVersion: v1
kind: Service
metadata:
  name: ceo-service
  namespace: ci-cd-demo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000  # <--- Yahan 3000 fix kar do, kyunki app 3000 par hai
      nodePort: 30005
  selector:
    app: ceo-backend
